// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAUzrXkwo5yC-L7XSrV_wuBtnF1D5dFJUs',
    appId: '1:506382140602:web:09c04057197b4f4675ee83',
    messagingSenderId: '506382140602',
    projectId: 'book-adaptation-review',
    authDomain: 'book-adaptation-review.firebaseapp.com',
    storageBucket: 'book-adaptation-review.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDjhzwWODObjIekR0QmUqHanUYbX0ZxKjE',
    appId: '1:506382140602:android:f27eedb6b4a4741375ee83',
    messagingSenderId: '506382140602',
    projectId: 'book-adaptation-review',
    storageBucket: 'book-adaptation-review.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBMbpY5ZLxt_70tv7_lgpydq5fXckLfB70',
    appId: '1:506382140602:ios:f48f8dd8c047aa9975ee83',
    messagingSenderId: '506382140602',
    projectId: 'book-adaptation-review',
    storageBucket: 'book-adaptation-review.appspot.com',
    iosBundleId: 'com.example.bookReview',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBMbpY5ZLxt_70tv7_lgpydq5fXckLfB70',
    appId: '1:506382140602:ios:f48f8dd8c047aa9975ee83',
    messagingSenderId: '506382140602',
    projectId: 'book-adaptation-review',
    storageBucket: 'book-adaptation-review.appspot.com',
    iosBundleId: 'com.example.bookReview',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAUzrXkwo5yC-L7XSrV_wuBtnF1D5dFJUs',
    appId: '1:506382140602:web:773609fa2a9423f775ee83',
    messagingSenderId: '506382140602',
    projectId: 'book-adaptation-review',
    authDomain: 'book-adaptation-review.firebaseapp.com',
    storageBucket: 'book-adaptation-review.appspot.com',
  );
}
